version: '3'
services:
  bot:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PORT=8000

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eneasredpill
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres-data:
